version: '3.8'
services:
  python3:
    restart: always
    build: 
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: 'Docker_python'
    env_file: 
      - ../.env
    working_dir: '/usr/src/app'
    tty: true
    volumes:
      - ../project:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS = *
      - RUNSERVER_ADDR=0.0.0.0
      - RUNSERVER_PORT=8000
